# Generated by Django 4.2.16 on 2026-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='assigned_technician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='assigned_technician_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
