# Generated by Django 4.2.16 on 2026-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_customization_cost_accepted_repair_cost_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='client_counter_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='client_negotiation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='client_counter_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='client_negotiation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
